### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by didymus707**
done with the sign-up page. Ready for review

### CODE REVIEW

**Comment by shloch** [comment]
### Pull request under review by SHEY LOUIS

**Comment by shloch** [comment]
GREAT JOB GUYS...👏 👏 

You have done considerable job, but please i need you to bring some changes

CHANGES REQUIRED

- validate STICKLER errors
- MINT, QUICKBOOKS & TURBO TAX logos should be images, while the text should be text besides these logos

With that done, we'll be good

Please correct these minor changes and file for review

**Comment by didymus707** [comment]
Images and texts have been added and all stickler errors fixed

**Comment by Anna-Myzukina** [comment]
### Pull request under review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!  Great job image

Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this! 

### The project is approved!
### You can merge this pull request!  image

*Happy coding 😄*

**Review by Anna-Myzukina — APPROVED** [review]
The project is approved!

**Pull request merged**
